# Generated by Django 3.2 on 2021-04-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaChats', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ip_add',
            field=models.CharField(default="", max_length=50),
        ),
    ]
