# Generated by Django 3.2 on 2021-04-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaChats', '0003_chat_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='ip_add',
        ),
    ]
