# Generated by Django 3.2 on 2021-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaChats', '0004_remove_chat_ip_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ip_address',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
