# Generated by Django 3.2 on 2021-04-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaChats', '0006_auto_20210430_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='person',
            field=models.CharField(max_length=30),
        ),
    ]
